name: Deploy to slow.fyi
on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: cd .github/deploy && npm install & cd ../.. && node .github/deploy/deploy.js
